apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: SWAVE-front
  namespace: front
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: front
    server: {{ .Values.spec.destination.server }}
  project: front
  source:
    path: apps
    repoURL: https://github.com/KEA-SWAVE-SURVEY/argocd-front
    targetRevision: HEAD
