apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-running.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd
  name: SWAVE-front
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: front
  source:
    path: apps
    repoURL: https://github.com/KEA-SWAVE-SURVEY/argocd-front
    targetRevision: HEAD
