apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-front
  name: user-front # deployment의 이름
spec:
  #replicas: 2 #hpa
  selector:
    matchLabels:
      app: user-front
  template:
    metadata:
      labels:
        app: user-front # pod의 label을 지정
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
        - name: user-front
          image: kjk7212/user-front:82
          ports:
            - name: user-front
              containerPort: 3000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
        - name: front-exporter
          image: 'nginx/nginx-prometheus-exporter:0.10.0'
          args:
            - '-nginx.scrape-uri=http://localhost:3000/metrics'
          ports:
            - name: ngnix-exporter
              containerPort: 9113

---

apiVersion: v1
kind: Service
metadata:
  name: user-front-service
  labels:
    app: user-front-service # service의 레이블
spec:
  type: ClusterIP
  ports:
  - name: front
    protocol: TCP
    port: 3000 # service의 port
    targetPort: 3000 # pod의 target port
  - name: ngnix-exporter
    protocol: TCP 
    port: 9113 # service의 port
    targetPort: 9113 # pod의 target port
  selector:
    app: user-front # 연결 시킬 pod의 label
